# === Padding & Offset Configuration ===
padding: 20

offsets:
  title: 10
  table: 5
  figure: 5
  text: 3

# === OCR Configuration ===
ocr:
  lang: "ch"
  use_doc_orientation_classify: true
  use_doc_unwarping: true
  use_textline_orientation: true
  text_det_unclip_ratio: 2.0
  text_det_box_thresh: 0.8
  text_rec_score_thresh: 0.8
